name: Build DQ Tool Exe

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시할 때 실행
  workflow_dispatch:      # 수동으로 빌드 버튼을 누를 수도 있게 설정

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        # --noconsole: 검은 창 방지, --onefile: 단일 파일 생성
        pyinstaller --noconsole --onefile --clean DQ.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DQ_Analyzer_Windows
        path: dist/DQ.exe
